name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to VPS (excluding vendor/, node_modules/, and media/)
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H vps.latelier22.fr >> ~/.ssh/known_hosts
        rsync -avz --exclude 'vendor/' --exclude 'node_modules/' --exclude 'public/media/' --delete ./ debian@vps.latelier22.Fr:/home/debian/kokoe/

    - name: Install PHP dependencies
      run: |
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "cd /home/debian/kokoe && composer install"

    - name: Install Node dependencies and build assets
      run: |
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "cd /home/debian/kokoe && sudo pnpm i && sudo pnpm run build"

    - name: Restart Nginx
      run: |
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "sudo systemctl restart nginx"
