name: Deploy to VPS

on:
  push:
    branches:
      - prod  # Déployer uniquement lors d'un push vers la branche 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key for secure connection
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H vps.latelier22.fr >> ~/.ssh/known_hosts

    - name: Copy files to VPS (excluding vendor/, node_modules/, and media/)
      run: |
        rsync -avz --exclude 'vendor/' --exclude 'node_modules/' --exclude 'public/media/' --delete ./ debian@vps.latelier22.fr:/home/debian/kokoe/

    - name: Install PHP dependencies
      run: |
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "cd /home/debian/kokoe && composer install --no-dev --optimize-autoloader"

    - name: Install Node dependencies and build assets
      run: |
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "cd /home/debian/kokoe && sudo pnpm i && sudo pnpm run build"

    - name: Set permissions
      run: |
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "sudo chown -R www-data:www-data /home/debian/kokoe"
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "sudo chmod -R 775 /home/debian/kokoe"
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "sudo chown -R www-data:www-data /home/debian/kokoe/public/media"
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "sudo chmod -R 775 /home/debian/kokoe/public/media"
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "sudo chmod -R 777 /home/debian/kokoe/var/cache"
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "sudo chown -R www-data:www-data /home/debian/kokoe/var/cache"
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "sudo chmod -R 777 /home/debian/kokoe/var/log"
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "sudo chown -R www-data:www-data /home/debian/kokoe/var/log"

    - name: Set environment to production
      run: |
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "cp /home/debian/kokoe/.env.prod /home/debian/kokoe/.env"

    - name: Restart Nginx
      run: |
        ssh -i ~/.ssh/id_rsa debian@vps.latelier22.fr "sudo systemctl restart nginx"

    - name: Deploy complete
      run: echo "Deployment completed successfully on the VPS!"
